### ISSUE TITLE
cl:tree-equal mishandles keyword arguments

### ISSUE THREAD

**Issue by davidmullen** [jcbeaudoin/MKCL#27]
```
> (tree-equal 'a 'a)

Debugger called in: #<thread "Initial" active (4318) 0x7f859043e740 7f858d9f3000>.

#<a SIMPLE-ERROR 140211509202688>:
    Both :TEST and :TEST-NOT are specified.
```

This bug can cause a crash.

**Comment by jcbeaudoin** [comment]
I guess that getting rid of the dpp utility was much too massive a change to happen really smoothly.  Too many loose ends to not miss a few.  But I still think it was a very valuable step since it recovered usable source code debugging in gdb.

In any case, thank you very much for the catch.  It was indeed a potential crash source.

**Comment by jcbeaudoin** [comment]
should be fixed now with your PR code but I spotted something in pairlist I'll fix soon.

Please check and close the issue if ok.

**Comment by jcbeaudoin** [comment]
`mk_cl_pairlis` was already fixed by a previous commit.

Should we close the issue?

**Comment by davidmullen** [comment]
Yes, `pairlis` looks OK.
